{% set name = "signac-dashboard" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_rev: v{{ version }}
  git_url: https://bitbucket.org/glotzer/signac-dashboard.git

build:
  number: 0
  skip: True  # [py<34]

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - signac >=0.8
    - flask
    - flask-assets
    - webassets >=0.12.1
    - flask-turbolinks
    - libsass
    - jsmin
    - cssmin

test:
  imports:
    - signac_dashboard
  source_files:
    - signac_dashboard/**
    - test.sh
    - tests/**

about:
  home: https://bitbucket.org/glotzer/signac-dashboard
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Search and browse through signac data spaces in the browser.'
  description: |
    Data visualization, analysis, and "dashboard" monitoring tool
    as part of the signac framework. The signac-dashboard interface
    allows users to rapidly view data managed in a signac project.
  doc_url: https://signac-dashboard.readthedocs.io/en/latest
  dev_url: https://bitbucket.org/glotzer/signac-dashboard/src

extra:
  recipe-maintainers:
    - csadorf
    - bdice
