{% set name = "signac-dashboard" %}
{% set version = "0.1.6" %}
{% set sha256 = "fe90ceda94e9092b5f04c37d9db78164a97a51a7b7e230e0e7153bb0fc575e0c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://glotzerlab.engin.umich.edu/Downloads/{{ name }}/{{ name }}-v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1001
  script: "{{ PYTHON }} -m pip install . --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python >=3.4
    - setuptools
    - pip
  run:
    - python >=3.4
    - signac >=0.8
    - flask >=0.12
    - flask-assets
    - webassets >=0.12.1
    - flask-turbolinks
    - libsass
    - jsmin

test:
  imports:
    - signac_dashboard

about:
  home: https://signac.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Search and browse through signac data spaces in the browser.'
  description: |
    Data visualization, analysis, and "dashboard" monitoring tool
    as part of the signac framework. The signac-dashboard interface
    allows users to rapidly view data managed in a signac project.
  doc_url: https://docs.signac.io
  dev_url: https://github.com/glotzerlab/signac-dashboard

extra:
  recipe-maintainers:
    - csadorf
    - bdice
