{% set name = "signac-dashboard" %}
{% set version = "0.2.7" %}
{% set sha256 = "5138792633b43ffb40b5dc133a3a45e97cbc8059245501cea909ec1f26db5b56" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/s/signac-dashboard/signac-dashboard-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.5
    - setuptools
    - pip
  run:
    - flask >=1.0
    - flask-assets >=2.0
    - flask-turbolinks
    - jsmin
    - libsass
    - natsort
    - python >=3.5
    - signac >=1.0
    - watchdog
    - webassets >=2.0
    - werkzeug >=1.0

test:
  imports:
    - signac_dashboard

about:
  home: https://signac.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'signac-dashboard: data visualization for signac'
  description: |
    Built on top of the signac framework, signac-dashboard allows
    users to rapidly visualize and analyze data managed in a signac
    project.
  doc_url: https://docs.signac.io
  dev_url: https://github.com/glotzerlab/signac-dashboard

extra:
  recipe-maintainers:
    - csadorf
    - bdice
