{% set name = "signac-dashboard" %}
{% set version = "0.2.1" %}
{% set sha256 = "3b3c72202555f963a26ea29f5a92c28a620120b3c0d20ff90ab1f37c3f70fe7a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://glotzerlab.engin.umich.edu/Downloads/{{ name }}/{{ name }}-v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python >=3.4
    - setuptools
    - pip
  run:
    - python >=3.4
    - signac >=0.8
    - flask >=0.12
    - flask-assets
    - webassets >=0.12.1
    - flask-turbolinks
    - libsass
    - jsmin
    - natsort

test:
  imports:
    - signac_dashboard

about:
  home: https://signac.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'signac-dashboard: data visualization for signac'
  description: |
    Built on top of the signac framework, signac-dashboard allows
    users to rapidly visualize and analyze data managed in a signac
    project.
  doc_url: https://docs.signac.io
  dev_url: https://github.com/glotzerlab/signac-dashboard

extra:
  recipe-maintainers:
    - csadorf
    - bdice
