{% set name = "signac-dashboard" %}
{% set version = "0.2.5" %}
{% set sha256 = "751e73e89cb8eb686a22619b436bf8c6ca10f53a3e03d305fb0382240f4a60ff" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://glotzerlab.engin.umich.edu/Downloads/{{ name }}/{{ name }}-v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.4
    - setuptools
    - pip
  run:
    - flask >=0.12
    - flask-assets
    - flask-turbolinks
    - jsmin
    - libsass
    - natsort
    - python >=3.4
    - signac >=0.8
    - watchdog
    - webassets >=0.12.1

test:
  imports:
    - signac_dashboard

about:
  home: https://signac.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'signac-dashboard: data visualization for signac'
  description: |
    Built on top of the signac framework, signac-dashboard allows
    users to rapidly visualize and analyze data managed in a signac
    project.
  doc_url: https://docs.signac.io
  dev_url: https://github.com/glotzerlab/signac-dashboard

extra:
  recipe-maintainers:
    - csadorf
    - bdice
